bookstore/Controllers/AuthorController.cs
using bookstore.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace bookstore.Controllers
{
    public class AuthorController : Controller
    {
        private static readonly HttpClient client;
        private JavaScriptSerializer jss = new JavaScriptSerializer();

        static AuthorController()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:44383/api/authorsdata/");
        }

        // GET: Author/List
        public ActionResult List()
        {
            string url = "listauthors";
            HttpResponseMessage response = client.GetAsync(url).Result;
            IEnumerable<AuthorDto> authors = response.Content.ReadAsAsync<IEnumerable<AuthorDto>>().Result;

            return View(authors);
        }

        // GET: Author/Details/5
        public ActionResult Details(int id)
        {
            string url = "findauthor/"+id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            AuthorDto selectedAuthor = response.Content.ReadAsAsync<AuthorDto>().Result;

            return View(selectedAuthor);
        }

        public ActionResult Error()
        {
            return View();
        }

        // GET: Author/New
        public ActionResult New()
        {
            return View();
        }

        // POST: Author/Create
        [HttpPost]
        public ActionResult Create(Author author)
        {
            string url = "addauthor";
            string jsonpayload = jss.Serialize(author);
            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Author/Edit/5
        public ActionResult Edit(int id)
        {
            string url = "findauthor/"+id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            AuthorDto selectedAuthor = response.Content.ReadAsAsync<AuthorDto>().Result;

            return View(selectedAuthor);
        }

        // POST: Author/Update/5
        [HttpPost]
        public ActionResult Update(int id, Author author)
        {
            string url = "updateauthor/"+ id;
            string jsonpayload = jss.Serialize(author);
            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            Debug.WriteLine(content);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Author/Delete/5
        public ActionResult ConfirmDelete(int id)
        {
            string url = "findauthor/"+id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            AuthorDto selectedAuthor = response.Content.ReadAsAsync<AuthorDto>().Result;

            return View(selectedAuthor);
        }

        // POST: Author/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            string url = "deleteauthor/" + id;
            HttpContent content = new StringContent("");
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
    }
}

bookstore/Controllers/BookController.cs
using bookstore.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace bookstore.Controllers
{
    public class BookController : Controller
    {
        private static readonly HttpClient client;
        private JavaScriptSerializer jss = new JavaScriptSerializer();

        static BookController()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:44383/api/");
        }
        // GET: Book/List
        public ActionResult List()
        {

            string url = "booksdata/listbooks";

            HttpResponseMessage response = client.GetAsync(url).Result;

            IEnumerable<BookDto> books = response.Content.ReadAsAsync<IEnumerable<BookDto>>().Result;

            return View(books);
        }

        // GET: Book/Details/5
        public ActionResult Details(int id)
        {

            string url = "booksdata/findbook/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;

            BookDto selectedBook = response.Content.ReadAsAsync<BookDto>().Result;
            Debug.WriteLine("Book received:");
            Debug.WriteLine(selectedBook.Title);

            return View(selectedBook);
        }

        public ActionResult Error()
        {
            return View();
        }

        // GET: Book/New
        public ActionResult New()
        {
            string url = "authorsdata/listauthors";
            HttpResponseMessage response = client.GetAsync(url).Result;
            IEnumerable<AuthorDto> AuthorOptions = response.Content.ReadAsAsync<IEnumerable<AuthorDto>>().Result;

            return View(AuthorOptions);
        }

        // POST: Book/Create
        [HttpPost]
        public ActionResult Create(Book book)
        {
            string url = "booksdata/addbook";
            string jsonpayload = jss.Serialize(book);
            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            } else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Book/Edit/5
        public ActionResult Edit(int id)
        {
            string url = "booksdata/findbook/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            BookDto selectedBook = response.Content.ReadAsAsync<BookDto>().Result;

            return View(selectedBook);
        }

        // POST: Book/Update/5
        [HttpPost]
        public ActionResult Update(int id, Book book)
        {
            string url = "booksdata/updatebook/" + id;
            string jsonpayload = jss.Serialize(book);
            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                var errorMessage = response.Content.ReadAsStringAsync().Result;
                Debug.WriteLine($"DELETE request failed with status code: {response.StatusCode}");
                Debug.WriteLine($"Error message: {errorMessage}");
                return RedirectToAction("Error");
            }
        }

        // GET: Book/Delete/5
        public ActionResult ConfirmDelete(int id)
        {
            string url = "booksdata/findbook/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            BookDto selectedBook = response.Content.ReadAsAsync<BookDto>().Result;

            return View(selectedBook);
        }

        // POST: Book/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            string url = "booksdata/deletebook/"+id;
            HttpContent content = new StringContent("");
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                var errorMessage = response.Content.ReadAsStringAsync().Result;
                Debug.WriteLine($"DELETE request failed with status code: {response.StatusCode}");
                Debug.WriteLine($"Error message: {errorMessage}");
                return RedirectToAction("Error");
            }
        }
    }
}

bookstore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace bookstore.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            return View();
        }
    }
}

bookstore/Controllers/RentalController.cs
using bookstore.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace bookstore.Controllers
{
    public class RentalController : Controller
    {
        private static readonly HttpClient client;
        private JavaScriptSerializer jss = new JavaScriptSerializer();

        static RentalController()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:44383/api/"); 
        }

        // GET: Rental/List
        public ActionResult List()
        {
            string url = "rentalsdata/listrentals";
            HttpResponseMessage response = client.GetAsync(url).Result;
            IEnumerable<RentalDto> rentals = response.Content.ReadAsAsync<IEnumerable<RentalDto>>().Result;

            return View(rentals);
        }

        // GET: Rental/Details/5
        public ActionResult Details(int id)
        {
            string url = "rentalsdata/findrental/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            RentalDto selectedRental = response.Content.ReadAsAsync<RentalDto>().Result;

            return View(selectedRental);
        }

        public ActionResult Error()
        {
            return View();
        }

        // GET: Rental/New
        public ActionResult New()
        {
            string url = "booksdata/listbooks";
            HttpResponseMessage response = client.GetAsync(url).Result;
            IEnumerable<BookDto> BookOptions = response.Content.ReadAsAsync<IEnumerable<BookDto>>().Result;

            return View(BookOptions);
        }

        // POST: Rental/Create
        [HttpPost]
        public ActionResult Create(Rental rental)
        {
            string url = "rentalsdata/addrental";
            string jsonpayload = jss.Serialize(rental);
            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Rental/Edit/5
        public ActionResult Edit(int id)
        {
            string url = "rentalsdata/findrental/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            RentalDto selectedRental = response.Content.ReadAsAsync<RentalDto>().Result;

            return View(selectedRental);
        }

        // POST: Rental/Update/5
        [HttpPost]
        public ActionResult Update(int id, Rental rental)
        {
            string url = "rentalsdata/updaterental/" + id;
            string jsonpayload = jss.Serialize(rental);
            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                var errorMessage = response.Content.ReadAsStringAsync().Result;
                Debug.WriteLine($"DELETE request failed with status code: {response.StatusCode}");
                Debug.WriteLine($"Error message: {errorMessage}");
                return RedirectToAction("Error");
            }
        }

        // GET: Rental/Delete/5
        public ActionResult ConfirmDelete(int id)
        {
            string url = "rentalsdata/findrental/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            RentalDto selectedRental = response.Content.ReadAsAsync<RentalDto>().Result;

            return View(selectedRental);
        }

        // POST: Rental/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            string url = "rentalsdata/deleterental/" + id;
            HttpContent content = new StringContent("");
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
    }
}

bookstore/Views/Home/Index.cshtml
<main>
    <header class="masthead">
        <div class="container position-relative">
            <div class="row justify-content-center">
                <div class="col-xl-6">
                    <div class="text-center text-white">
                        <h1 class="mb-5">Welcome to BookStore</h1>
                        <div class="d-flex justify-content-center mb-5">
                            <div>
                                <a href="@Url.Action("List", "Author")" class="btn btn-primary btn-md active" role="button">
                                    Browse Authors
                                </a>
                            </div>
                            <div class="px-2">
                                <a href="@Url.Action("New", "Book")" class="btn btn-success btn-md active" role="button">
                                    Publish Books
                                </a>
                            </div>
                            <a href="@Url.Action("New", "Rental")" class="btn btn-secondary btn-md active" role="button">
                                Rent a Book
                            </a>
                        </div>
                        @*<form class="">
                            <div class="row">
                                <div class="col">
                                    <input class="form-control form-control-lg" id="emailAddress" type="email" placeholder="Search" />
                                </div>
                                <div class="col">
                                    <button class="btn btn-primary btn-md" id="submitButton" type="submit">
                                        Submit
                                    </button>
                                </div>
                            </div>
                        </form>*@
                    </div>
                </div>
            </div>
        </div>
    </header>

    @*<div class="container bg-trasparent my-4 p-3">
        <div class="row row-cols-1 row-cols-xs-2 row-cols-sm-2 row-cols-lg-3 g-3">
            <div class="col">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Book title</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Available for rental</h6>
                        <p class="card-text">Book Price.</p>
                        <p class="card-text">Book ISBN</p>
                        <a href="#" class="card-link">Book Author</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card px-1" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Book title</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Available for rental</h6>
                        <p class="card-text">Book Price</p>
                        <p class="card-text">Book ISBN</p>
                        <a href="#" class="card-link">Book Author</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Book title</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Cannot rent</h6>
                        <p class="card-text">Book Price</p>
                        <p class="card-text">Book ISBN</p>
                        <a href="#" class="card-link">Book Author</a>
                    </div>
                </div>
            </div>
        </div>
    </div>*@
</main>